(() => {
  'use strict';
  const CONFIG = window.DPRO_HOMECARE_CONFIG || {};
  const API_BASE = String(CONFIG.API_BASE || '').replace(/\/+$/, '');
  const OFFICE_CODE = CONFIG.OFFICE_CODE || 'dpro_homecare_demo';
  const TIMEOUT = Number(CONFIG.REQUEST_TIMEOUT_MS || 15000);
  const STORAGE_KEY = CONFIG.OWNER_ADMIN_STORAGE_KEY || 'dpro_homecare_owner_admin_code';
  const params = new URLSearchParams(location.search);
  const demo = ['1','true','yes'].includes(String(params.get('demo') || '').toLowerCase());
  const state = { adminCode: '', data: null, selectedRecordId: null };
  const $ = (q, root = document) => root.querySelector(q);
  const $$ = (q, root = document) => [...root.querySelectorAll(q)];
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (ch) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));

  function ymd(date = new Date()) {
    const parts = new Intl.DateTimeFormat('en-CA', { timeZone:'Asia/Tokyo', year:'numeric', month:'2-digit', day:'2-digit' }).formatToParts(date);
    const map = Object.fromEntries(parts.filter((x) => x.type !== 'literal').map((x) => [x.type, x.value]));
    return `${map.year}-${map.month}-${map.day}`;
  }
  function formatDate(dateString) { return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date(`${dateString}T12:00:00+09:00`)); }
  function formatTime(iso) { return iso ? new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso)) : '--:--'; }
  function formatDateTime(iso) { return iso ? new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso)) : '未登録'; }
  function statusLabel(v){return ({scheduled:'予定',confirmed:'確認済み',in_progress:'訪問中',completed:'完了',cancelled:'キャンセル',no_show:'不在',suspended:'中止',submitted:'提出済み',returned:'差戻し',approved:'承認済み',pending:'承認待ち',published:'公開済み',open:'未対応',in_progress_inquiry:'対応中',waiting:'確認待ち',resolved:'解決',closed:'完了',investigating:'確認中',action_required:'対応必要'})[v] || v || '未設定';}
  function serviceLabel(v){return ({physical_care:'身体介護',daily_living:'生活援助',combined:'身体介護＋生活援助',outing:'通院・外出介助',self_pay:'自費サービス',other:'その他'})[v] || v || '未設定';}
  function roleLabel(v){return ({owner:'オーナー',manager:'管理者',service_coordinator:'サービス提供責任者',helper:'訪問介護員',clerk:'事務',viewer:'閲覧'})[v] || v || ''}
  function incidentLabel(v){return ({near_miss:'ヒヤリハット',fall:'転倒',injury:'外傷',medication_concern:'服薬に関する懸念',missing_item:'物品紛失',property_damage:'物損',complaint:'苦情',other:'その他'})[v] || v;}
  function officeNameHtml(value){
    const safe = escapeHtml(value || '訪問介護事業所');
    return safe
      .replace('DPRO訪問介護ステーション', 'DPRO訪問介護<wbr>ステーション')
      .replace('訪問介護ステーション', '訪問介護<wbr>ステーション');
  }
  function showToast(message, error=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error',error);el.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.hidden=true,4300);}
  function setLoading(active){$('#loadingOverlay').hidden=!active;}

  async function api(path, options={}) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), TIMEOUT);
    const url = new URL(`${API_BASE}${path}`);
    if (!url.searchParams.has('office_code')) url.searchParams.set('office_code', OFFICE_CODE);
    const headers = {'Content-Type':'application/json','X-Admin-Code':state.adminCode,...(options.headers||{})};
    try {
      const response = await fetch(url,{method:options.method||'GET',headers,signal:controller.signal,...(options.body===undefined?{}:{body:JSON.stringify(options.body)})});
      const data = await response.json().catch(()=>({}));
      if (!response.ok || data.ok===false) { const e=new Error(data.error||`通信エラー（${response.status}）`);e.status=response.status;throw e; }
      return data;
    } catch(error) {
      if (error.name==='AbortError') throw new Error('通信がタイムアウトしました。もう一度お試しください。');
      if (error.status===401) logout(false);
      throw error;
    } finally { clearTimeout(timer); }
  }

  function loginView(show){$('#loginPanel').hidden=!show;$('#ownerApp').hidden=show;$('#logoutButton').hidden=show;}
  async function login(event){event?.preventDefault();state.adminCode=$('#adminCode').value.trim();if(!state.adminCode)return showToast('管理コードを入力してください。',true);setLoading(true);try{await api('/admin/verify',{method:'POST',body:{admin_code:state.adminCode}});sessionStorage.setItem(STORAGE_KEY,state.adminCode);loginView(false);await loadOverview();showToast('管理画面を開きました。');}catch(e){showToast(e.message,true);loginView(true);}finally{setLoading(false);}}
  function logout(notify=true){state.adminCode='';state.data=null;sessionStorage.removeItem(STORAGE_KEY);$('#adminCode').value=demo?'1234':'';loginView(true);if(notify)showToast('ログアウトしました。');}

  async function loadOverview(){setLoading(true);try{const date=$('#workDate').value||ymd();const data=await api(`/admin/owner/overview?date=${encodeURIComponent(date)}`);state.data=data;renderAll(data);}catch(e){showToast(e.message,true);}finally{setLoading(false);}}
  function setSection(name){$$('.owner-section').forEach((el)=>el.classList.toggle('active',el.dataset.ownerSection===name));$$('.nav-button').forEach((el)=>el.classList.toggle('active',el.dataset.section===name));window.scrollTo({top:0,behavior:'smooth'});}
  function empty(text){return `<div class="empty-box">${escapeHtml(text)}</div>`;}
  function pill(text,type=''){return `<span class="status-pill ${type}">${escapeHtml(text)}</span>`;}

  function renderAll(data){
    $('#officeName').innerHTML=officeNameHtml(data.office?.office_name);$('#ownerDateLabel').textContent=formatDate(data.date);$('#demoBanner').hidden=!demo;
    $('#navRecordBadge').textContent=data.counts.pending_records||0;$('#navReportBadge').textContent=data.counts.pending_family_reports||0;$('#navHandoverBadge').textContent=data.counts.open_handovers||0;$('#navInquiryBadge').textContent=data.counts.open_inquiries||0;$('#navIncidentBadge').textContent=data.counts.open_incidents||0;
    renderSummary(data.counts);renderVisits(data.visits||[]);renderPriority(data);renderOfficeStatus(data);renderRecords(data.records||[]);renderReports(data.family_reports||[]);renderHandovers(data.handovers||[]);renderInquiries(data.inquiries||[]);renderIncidents(data.incidents||[]);renderStaff(data.staff||[]);
  }
  function renderSummary(c){const rows=[['本日の訪問',c.today_visits||0,''],['訪問中',c.in_progress||0,''],['未割当て',c.unassigned||0,c.unassigned?'alert':''],['記録確認',c.pending_records||0,c.pending_records?'alert':''],['家族公開',c.pending_family_reports||0,''],['事故・問い合わせ',(c.open_incidents||0)+(c.open_inquiries||0),(c.serious_incidents||c.urgent_inquiries)?'alert':'']];$('#summaryGrid').innerHTML=rows.map(([l,v,t])=>`<article class="summary-card ${t}"><span>${escapeHtml(l)}</span><strong>${Number(v)}</strong></article>`).join('');}
  function renderVisits(visits){$('#todayVisitList').innerHTML=visits.length?visits.map(v=>{const staff=(v.assignments||[]).map(a=>a.staff?.staff_name).filter(Boolean).join('、')||'未割当て';const type=['cancelled','no_show','suspended'].includes(v.status)?'danger':v.status==='in_progress'?'warning':'';return `<article class="timeline-item"><div class="timeline-time">${formatTime(v.planned_start)}<br><small>〜${formatTime(v.planned_end)}</small></div><div><strong>${escapeHtml(v.client?.client_name||'利用者')}</strong><div>${escapeHtml(serviceLabel(v.service_type))}・${escapeHtml(staff)}</div></div>${pill(statusLabel(v.status),type)}</article>`}).join(''):empty('この日の訪問はありません。');}
  function renderPriority(data){const rows=[];(data.incidents||[]).filter(x=>['high','critical'].includes(x.severity)).forEach(x=>rows.push(['事故・ヒヤリ',x.client?.client_name,x.fact_summary,'danger','incidents']));(data.inquiries||[]).filter(x=>['urgent','emergency'].includes(x.urgency)).forEach(x=>rows.push(['問い合わせ',x.client?.client_name,x.subject||x.detail,'danger','inquiries']));(data.handovers||[]).filter(x=>x.importance==='urgent').forEach(x=>rows.push(['申し送り',x.client?.client_name,x.title,'warning','handovers']));if(!rows.length){$('#priorityList').innerHTML=empty('緊急対応が必要な項目はありません。');return;}$('#priorityList').innerHTML=rows.map(([k,n,d,t,sec])=>`<button class="work-item" type="button" data-jump="${sec}"><div class="work-main"><h3>${escapeHtml(k)}・${escapeHtml(n||'')}</h3><p>${escapeHtml(d||'')}</p></div>${pill('要確認',t)}</button>`).join('');$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>setSection(b.dataset.jump)));}
  function renderOfficeStatus(data){const c=data.counts;$('#officeStatus').innerHTML=[['利用中の利用者',c.active_clients||0],['有効スタッフ',c.active_staff||0],['未解決申し送り',c.open_handovers||0],['差戻し記録',c.returned_records||0]].map(([l,v])=>`<div class="metric-row"><span>${escapeHtml(l)}</span><strong>${Number(v)}</strong></div>`).join('');}
  function renderRecords(rows){$('#recordList').innerHTML=rows.length?rows.map(r=>`<article class="work-item"><div class="work-main"><h3>${escapeHtml(r.client?.client_name||'利用者')}・${formatDateTime(r.visit?.planned_start)}</h3><p>${escapeHtml(serviceLabel(r.visit?.service_type))}／提出者 ${escapeHtml(r.created_by_staff?.staff_name||'スタッフ')}</p><p class="work-detail">${escapeHtml(r.service_summary||'実施内容未入力')}</p></div><div class="work-actions">${pill(statusLabel(r.record_status),r.record_status==='returned'?'danger':'warning')}<button class="button button-primary button-small" data-record-id="${r.id}" type="button">記録を確認</button></div></article>`).join(''):empty('確認待ちの訪問記録はありません。');$$('[data-record-id]').forEach(b=>b.addEventListener('click',()=>openRecord(b.dataset.recordId)));}
  function renderReports(rows){$('#reportList').innerHTML=rows.length?rows.map(r=>{const canPublish=r.record_status==='approved';return `<article class="work-item"><div class="work-main"><h3>${escapeHtml(r.client?.client_name||'利用者')}・${escapeHtml(r.report_title)}</h3><p>${formatDateTime(r.visit?.planned_start)}／記録状態 ${escapeHtml(statusLabel(r.record_status))}</p><p class="work-detail">${escapeHtml(r.public_comment)}</p></div><div class="work-actions">${pill(statusLabel(r.approval_status),'warning')}<button class="button button-danger button-small" data-report-reject="${r.id}" type="button">非公開</button><button class="button button-primary button-small" data-report-publish="${r.id}" type="button" ${canPublish?'':'disabled'}>${canPublish?'家族へ公開':'記録承認待ち'}</button></div></article>`}).join(''):empty('家族公開の承認待ちはありません。');$$('[data-report-publish]').forEach(b=>b.addEventListener('click',()=>reportAction(b.dataset.reportPublish,'publish')));$$('[data-report-reject]').forEach(b=>b.addEventListener('click',()=>reportAction(b.dataset.reportReject,'reject')));}
  function renderHandovers(rows){$('#handoverListOwner').innerHTML=rows.length?rows.map(h=>`<article class="work-item"><div class="work-main"><h3>${escapeHtml(h.client?.client_name||'利用者')}・${escapeHtml(h.title)}</h3><p>${escapeHtml(h.created_by_staff?.staff_name||'スタッフ')}／${formatDateTime(h.created_at)}</p><p class="work-detail">${escapeHtml(h.note_text)}</p></div><div class="work-actions"><span class="importance-pill ${h.importance}">${escapeHtml(h.importance==='urgent'?'緊急':h.importance==='high'?'重要':'通常')}</span><button class="button button-primary button-small" data-handover-resolve="${h.id}" type="button">対応済みにする</button></div></article>`).join(''):empty('未解決の申し送りはありません。');$$('[data-handover-resolve]').forEach(b=>b.addEventListener('click',()=>resolveHandover(b.dataset.handoverResolve)));}
  function staffOptions(selected){return `<option value="">未割当て</option>${(state.data?.staff||[]).filter(s=>s.is_active).map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>${escapeHtml(s.staff_name)}</option>`).join('')}`;}
  function renderInquiries(rows){$('#inquiryList').innerHTML=rows.length?rows.map(q=>`<article class="work-item"><div class="work-main"><h3>${escapeHtml(q.client?.client_name||'利用者未指定')}・${escapeHtml(q.subject||q.inquiry_type)}</h3><p>${escapeHtml(q.channel)}／${formatDateTime(q.created_at)}</p><p class="work-detail">${escapeHtml(q.detail)}</p></div><div class="work-actions"><select data-inquiry-status="${q.id}"><option value="open" ${q.status==='open'?'selected':''}>未対応</option><option value="in_progress" ${q.status==='in_progress'?'selected':''}>対応中</option><option value="waiting" ${q.status==='waiting'?'selected':''}>確認待ち</option><option value="resolved">解決</option><option value="closed">完了</option></select><select data-inquiry-staff="${q.id}">${staffOptions(q.assigned_staff_id)}</select><button class="button button-primary button-small" data-inquiry-save="${q.id}" type="button">保存</button></div></article>`).join(''):empty('未完了の問い合わせはありません。');$$('[data-inquiry-save]').forEach(b=>b.addEventListener('click',()=>updateInquiry(b.dataset.inquirySave)));}
  function renderIncidents(rows){$('#incidentList').innerHTML=rows.length?rows.map(i=>`<article class="work-item"><div class="work-main"><h3>${escapeHtml(i.client?.client_name||'利用者')}・${escapeHtml(incidentLabel(i.incident_type))}</h3><p>重大度 ${escapeHtml(i.severity)}／${formatDateTime(i.occurred_at)}／報告 ${escapeHtml(i.reported_by_staff?.staff_name||'スタッフ')}</p><p class="work-detail">${escapeHtml(i.fact_summary)}\n初期対応：${escapeHtml(i.initial_response||'未記録')}</p></div><div class="work-actions"><select data-incident-status="${i.id}"><option value="open" ${i.manager_status==='open'?'selected':''}>未確認</option><option value="investigating" ${i.manager_status==='investigating'?'selected':''}>確認中</option><option value="action_required" ${i.manager_status==='action_required'?'selected':''}>対応必要</option><option value="closed">完了</option></select><select data-incident-family="${i.id}"><option value="not_required" ${i.family_contact_status==='not_required'?'selected':''}>家族連絡不要</option><option value="pending" ${i.family_contact_status==='pending'?'selected':''}>家族連絡待ち</option><option value="contacted" ${i.family_contact_status==='contacted'?'selected':''}>家族連絡済み</option><option value="unable_to_contact" ${i.family_contact_status==='unable_to_contact'?'selected':''}>連絡つかず</option></select><button class="button button-primary button-small" data-incident-save="${i.id}" type="button">対応を保存</button></div></article>`).join(''):empty('未完了の事故・ヒヤリハットはありません。');$$('[data-incident-save]').forEach(b=>b.addEventListener('click',()=>updateIncident(b.dataset.incidentSave)));}
  function renderStaff(rows){$('#staffListOwner').innerHTML=rows.length?rows.map(s=>`<article class="staff-card"><h3>${escapeHtml(s.staff_name)}</h3><p>${escapeHtml(s.staff_code)}・${escapeHtml(roleLabel(s.primary_role))}</p><p>${escapeHtml(s.qualification||'資格未登録')}</p>${pill(s.is_active?'稼働中':'停止',s.is_active?'':'danger')}</article>`).join(''):empty('スタッフが登録されていません。');}

  async function openRecord(id){setLoading(true);try{const data=await api(`/admin/owner/records/${id}`);state.selectedRecordId=id;const r=data.record,v=data.visit,c=data.client;$('#recordDialogTitle').textContent=`${c?.client_name||'利用者'} 様の訪問記録`;$('#recordDialogMeta').textContent=`${formatDateTime(v?.planned_start)}・${serviceLabel(v?.service_type)}・${statusLabel(r.record_status)}`;$('#recordReviewComment').value=r.return_reason||'';$('#recordDialogContent').innerHTML=`<div class="detail-grid"><div class="detail-block"><h3>利用者の様子</h3><p>${escapeHtml(r.client_condition||'未入力')}</p></div><div class="detail-block"><h3>実施内容</h3><p>${escapeHtml(r.service_summary||'未入力')}</p></div></div><div class="detail-block"><h3>実施項目</h3>${(data.items||[]).map(x=>`<div class="record-item"><span>${escapeHtml(x.item_name)}${x.note?`・${escapeHtml(x.note)}`:''}</span><strong>${escapeHtml(({done:'実施',partial:'一部',not_done:'未実施',not_applicable:'対象外'})[x.result]||x.result)}</strong></div>`).join('')||'登録なし'}</div><div class="detail-block internal-block"><h3>職員内部のみ</h3><p>${escapeHtml(r.internal_handover||'内部申し送りなし')}</p><p>次回注意：${escapeHtml(r.next_visit_attention||'なし')}</p><p>利用者内部注意：${escapeHtml(c?.internal_attention||'なし')}</p></div><div class="detail-block family-block"><h3>家族へ公開候補</h3><p>${escapeHtml(r.family_public_comment||'公開コメントなし')}</p></div>`;$('#recordDialog').showModal();}catch(e){showToast(e.message,true);}finally{setLoading(false);}}
  async function recordAction(action){const comment=$('#recordReviewComment').value.trim();if(action==='return'&&!comment)return showToast('差戻し理由を入力してください。',true);if(!confirm(action==='approve'?'この訪問記録を承認しますか？':'この訪問記録を差戻しますか？'))return;await runAction(`/admin/owner/records/${state.selectedRecordId}/${action}`,{comment},action==='approve'?'訪問記録を承認しました。':'訪問記録を差戻しました。');$('#recordDialog').close();}
  async function reportAction(id,action){let comment='';if(action==='reject'){comment=prompt('非公開理由を入力してください。')||'';if(!comment)return;}if(action==='publish'&&!confirm('この内容を家族画面へ公開しますか？'))return;await runAction(`/admin/owner/family-reports/${id}/${action}`,{comment},action==='publish'?'家族画面へ公開しました。':'家族報告を非公開にしました。');}
  async function resolveHandover(id){if(!confirm('この申し送りを対応済みにしますか？'))return;await runAction(`/admin/owner/handovers/${id}/resolve`,{},'申し送りを対応済みにしました。');}
  async function updateInquiry(id){const status=$(`[data-inquiry-status="${id}"]`).value,assigned_staff_id=$(`[data-inquiry-staff="${id}"]`).value||null;await runAction(`/admin/owner/inquiries/${id}/update`,{status,assigned_staff_id},'問い合わせを更新しました。');}
  async function updateIncident(id){const manager_status=$(`[data-incident-status="${id}"]`).value,family_contact_status=$(`[data-incident-family="${id}"]`).value;const action_detail=prompt('今回の確認・対応内容を入力してください。（任意）')||'';await runAction(`/admin/owner/incidents/${id}/update`,{manager_status,family_contact_status,action_detail},'事故・ヒヤリハット対応を更新しました。');}
  async function runAction(path,body,message){setLoading(true);try{await api(path,{method:'POST',body});showToast(message);await loadOverview();}catch(e){showToast(e.message,true);}finally{setLoading(false);}}

  async function searchClients(event){event.preventDefault();const q=$('#clientSearchInput').value.trim();if(!q)return showToast('検索文字を入力してください。',true);setLoading(true);try{const data=await api(`/admin/clients/search?q=${encodeURIComponent(q)}`);$('#clientSearchResult').innerHTML=data.clients.length?data.clients.map(c=>`<article class="work-item"><div class="work-main"><h3>${escapeHtml(c.client_name)}・${escapeHtml(c.client_number)}</h3><p>${escapeHtml(c.status)}／${escapeHtml(c.phone||'電話未登録')}</p><p>${escapeHtml([c.address,c.building_room].filter(Boolean).join(' '))}</p><p>家族：${escapeHtml((c.families||[]).map(f=>`${f.family_name}（${f.relationship||'続柄未登録'}）`).join('、')||'未登録')}</p></div></article>`).join(''):empty('該当する利用者はいません。');}catch(e){showToast(e.message,true);}finally{setLoading(false);}}

  function bind(){
    $('#loginForm').addEventListener('submit',login);$('#clearAdminCode').addEventListener('click',()=>{$('#adminCode').value='';$('#adminCode').focus();});$('#logoutButton').addEventListener('click',()=>logout());$('#reloadButton').addEventListener('click',()=>state.adminCode?loadOverview():login());$('#workDate').addEventListener('change',loadOverview);$$('.nav-button').forEach(b=>b.addEventListener('click',()=>setSection(b.dataset.section)));$('#clientSearchForm').addEventListener('submit',searchClients);$('#closeRecordDialog').addEventListener('click',()=>$('#recordDialog').close());$('#approveRecordButton').addEventListener('click',()=>recordAction('approve'));$('#returnRecordButton').addEventListener('click',()=>recordAction('return'));$('#recordDialog').addEventListener('click',(e)=>{if(e.target===$('#recordDialog'))$('#recordDialog').close();});
  }
  async function init(){bind();$('#workDate').value=ymd();$('#systemCheckLink').href=`${API_BASE}/system-check`;$('#adminCode').value=demo?'1234':'';$('#demoBanner').hidden=!demo;const saved=sessionStorage.getItem(STORAGE_KEY);if(saved)$('#adminCode').value=saved;if(demo||saved)await login();else loginView(true);}
  init().catch(e=>showToast(e.message,true));
})();
