// DPRO 訪問介護・家族連絡 LINE
// STEP HOMECARE-14: 訪問記録検索・CSV・印刷・保存運用
(() => {
  'use strict';
  const CONFIG=window.DPRO_HOMECARE_CONFIG||{};
  const API_BASE=String(CONFIG.API_BASE||'').replace(/\/+$/,'');
  const OFFICE_CODE=CONFIG.OFFICE_CODE||'dpro_homecare_demo';
  const TIMEOUT=Number(CONFIG.REQUEST_TIMEOUT_MS||15000);
  const STORAGE_KEY=CONFIG.ADMIN_SESSION_STORAGE_KEY||'dpro_homecare_admin_session';
  const params=new URLSearchParams(location.search);
  const demo=['1','true','yes'].includes(String(params.get('demo')||'').toLowerCase());
  const PAGE_SIZE=50;
  const state={adminSession:'',options:null,result:null,offset:0,selectedDetail:null};
  const $=(q,r=document)=>r.querySelector(q);const $$=(q,r=document)=>[...r.querySelectorAll(q)];
  const esc=(v)=>String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const serviceLabel=(v)=>({physical_care:'身体介護',daily_living:'生活援助',combined:'身体介護＋生活援助',outing:'通院・外出介助',self_pay:'自費サービス',other:'その他'})[v]||v||'未設定';
  const statusLabel=(v)=>({draft:'下書き',submitted:'提出済み',returned:'差戻し',approved:'承認済み'})[v]||v||'未設定';
  function ymd(date=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const m=Object.fromEntries(p.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`}
  function addDays(dateString,days){const d=new Date(`${dateString}T12:00:00+09:00`);d.setUTCDate(d.getUTCDate()+days);return ymd(d)}
  function formatDateTime(iso){return iso?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso)):'未登録'}
  function duration(start,end){const n=Math.round((new Date(end)-new Date(start))/60000);return Number.isFinite(n)&&n>0?`${n}分`:'時間未登録'}
  function toast(message,error=false){const e=$('#toast');e.textContent=message;e.classList.toggle('error',error);e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,4500)}
  function loading(active){$('#loadingOverlay').hidden=!active}
  function loginView(show){$('#loginPanel').hidden=!show;$('#recordsApp').hidden=show;$('#logoutButton').hidden=show}
  async function api(path,options={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),TIMEOUT);const url=new URL(`${API_BASE}${path}`);if(!url.searchParams.has('office_code'))url.searchParams.set('office_code',OFFICE_CODE);const headers={'Content-Type':'application/json','X-Admin-Session':state.adminSession,...(options.headers||{})};try{const r=await fetch(url,{method:options.method||'GET',headers,signal:c.signal,...(options.body===undefined?{}:{body:JSON.stringify(options.body)})});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false){const e=new Error(d.error||`通信エラー（${r.status}）`);e.status=r.status;throw e}return d}catch(e){if(e.name==='AbortError')throw new Error('通信がタイムアウトしました。もう一度お試しください。');if(e.status===401)logout(false);throw e}finally{clearTimeout(t)}}
  async function login(event){event?.preventDefault();const code=$('#adminCode').value.trim();if(!code)return toast('管理コードを入力してください。',true);loading(true);try{const r=await api('/admin/verify',{method:'POST',body:{admin_code:code,scope:'owner'}});state.adminSession=r.admin_session;sessionStorage.setItem(STORAGE_KEY,state.adminSession);$('#adminCode').value='';loginView(false);await loadInitial();toast('訪問記録管理を開きました。')}catch(e){toast(e.message,true);loginView(true)}finally{loading(false)}}
  async function logout(notify=true){const token=state.adminSession;state.adminSession='';state.options=null;state.result=null;sessionStorage.removeItem(STORAGE_KEY);$('#adminCode').value=demo?'1234':'';loginView(true);if(token){const u=new URL(`${API_BASE}/admin/logout`);u.searchParams.set('office_code',OFFICE_CODE);fetch(u,{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Session':token},body:'{}'}).catch(()=>{})}if(notify)toast('ログアウトしました。')}
  function fillOptions(data){state.options=data;$('#clientFilter').innerHTML='<option value="">すべて</option>'+data.clients.map(x=>`<option value="${esc(x.id)}">${esc(x.client_number)}　${esc(x.client_name)}</option>`).join('');$('#staffFilter').innerHTML='<option value="">すべて</option>'+data.staff.map(x=>`<option value="${esc(x.id)}">${esc(x.staff_code)}　${esc(x.staff_name)}${x.is_active?'':'（停止）'}</option>`).join('');$('#statusFilter').innerHTML='<option value="">すべて</option>'+data.statuses.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('')}
  function filters(){return{date_from:$('#dateFrom').value,date_to:$('#dateTo').value,client_id:$('#clientFilter').value,staff_id:$('#staffFilter').value,record_status:$('#statusFilter').value,q:$('#keywordFilter').value.trim()}}
  function queryString(extra={}){const q=new URLSearchParams({...filters(),...extra});[...q.keys()].forEach(k=>{if(q.get(k)==='')q.delete(k)});return q.toString()}
  function validateDates(){const a=$('#dateFrom').value,b=$('#dateTo').value;if(!a||!b)throw new Error('開始日と終了日を入力してください。');if(b<a)throw new Error('終了日は開始日以降にしてください。');const days=Math.round((new Date(`${b}T12:00:00+09:00`)-new Date(`${a}T12:00:00+09:00`))/86400000);if(days>366)throw new Error('一度に検索できる期間は367日以内です。')}
  function recordHtml(r){const staff=(r.assigned_staff||[]).map(x=>x.staff_name).filter(Boolean).join('、')||'担当未登録';return `<article class="record-row"><div class="record-date"><strong>${esc(formatDateTime(r.visit?.planned_start))}</strong><span>${esc(duration(r.visit?.planned_start,r.visit?.planned_end))}</span></div><div class="record-main"><h2>${esc(r.client?.client_name||'利用者')} <small>${esc(r.client?.client_number||'')}</small></h2><p>${esc(serviceLabel(r.visit?.service_type))}／担当 ${esc(staff)}</p><p class="record-summary">${esc(r.service_summary||'実施内容未入力')}</p><p class="record-staff">提出：${esc(r.submitted_by_staff?.staff_name||'未登録')}　確認：${esc(r.reviewed_by_staff?.staff_name||'未確認')}</p></div><div class="record-actions"><span class="status-pill ${esc(r.record_status)}">${esc(statusLabel(r.record_status))}</span><button class="button button-primary button-small" data-record-detail="${esc(r.id)}" type="button">詳細・印刷</button></div></article>`}
  function render(){const r=state.result||{records:[],total:0,offset:0,limit:PAGE_SIZE};$('#recordsList').innerHTML=r.records.length?r.records.map(recordHtml).join(''):'<div class="empty-state">条件に合う訪問記録はありません。</div>';const start=r.total?Number(r.offset)+1:0,end=Math.min(Number(r.offset)+r.records.length,Number(r.total));$('#resultTotal').textContent=`${r.total||0}件`;$('#resultRange').textContent=`${start}〜${end}件を表示`;const page=Math.floor(Number(r.offset||0)/PAGE_SIZE)+1;$('#pageLabel').textContent=`${page}ページ`;$('#prevPage').disabled=Number(r.offset||0)<=0;$('#nextPage').disabled=Number(r.offset||0)+r.records.length>=Number(r.total||0);$('#csvButton').disabled=!r.total;$('#printListButton').disabled=!r.records.length;$$('[data-record-detail]').forEach(b=>b.addEventListener('click',()=>openDetail(b.dataset.recordDetail)))}
  async function search(reset=false){try{validateDates()}catch(e){return toast(e.message,true)}if(reset)state.offset=0;loading(true);try{state.result=await api(`/admin/owner/record-search?${queryString({limit:PAGE_SIZE,offset:state.offset})}`);render()}catch(e){toast(e.message,true)}finally{loading(false)}}
  function detailMarkup(data,forPrint=false){const r=data.record||{},v=data.visit||{},c=data.client||{};const items=(data.items||[]).map(x=>`<div class="record-item"><span>${esc(x.item_name)}${x.note?`・${esc(x.note)}`:''}</span><strong>${esc(({done:'実施',partial:'一部',not_done:'未実施',not_applicable:'対象外'})[x.result]||x.result)}</strong></div>`).join('')||'登録なし';return `${forPrint?`<h1>${esc(c.client_name||'利用者')} 様　訪問記録</h1><p>${esc(formatDateTime(v.planned_start))}・${esc(serviceLabel(v.service_type))}・${esc(statusLabel(r.record_status))}</p>`:''}<div class="detail-grid"><div class="detail-block"><h3>利用者の様子</h3><p>${esc(r.client_condition||'未入力')}</p></div><div class="detail-block"><h3>実施内容</h3><p>${esc(r.service_summary||'未入力')}</p></div></div><div class="detail-block"><h3>実施項目</h3>${items}</div><div class="detail-block family"><h3>家族向け記録</h3><p>${esc(r.family_public_comment||'公開コメントなし')}</p></div><div class="detail-block internal"><h3>職員内部のみ</h3><p>${esc(r.internal_handover||'内部申し送りなし')}</p><p>次回注意：${esc(r.next_visit_attention||'なし')}</p><p>利用者内部注意：${esc(c.internal_attention||'なし')}</p></div>`}
  async function openDetail(id){loading(true);try{const d=await api(`/admin/owner/records/${id}`);state.selectedDetail=d;$('#dialogTitle').textContent=`${d.client?.client_name||'利用者'} 様の訪問記録`;$('#dialogMeta').textContent=`${formatDateTime(d.visit?.planned_start)}・${serviceLabel(d.visit?.service_type)}・${statusLabel(d.record?.record_status)}`;$('#dialogContent').innerHTML=detailMarkup(d);$('#recordDialog').showModal()}catch(e){toast(e.message,true)}finally{loading(false)}}
  async function logPrint(type,count,recordId=null){await api('/admin/owner/records/print-log',{method:'POST',body:{export_type:type,filters:{...filters(),record_id:recordId},record_count:count}})}
  async function printList(){if(!state.result?.records?.length)return;loading(true);try{await logPrint('print_list',state.result.records.length);$('#printMeta').textContent=`出力日時：${formatDateTime(new Date().toISOString())}\n検索期間：${$('#dateFrom').value} ～ ${$('#dateTo').value}　現在の表示 ${state.result.records.length}件／全${state.result.total}件`;document.body.classList.remove('printing-detail');window.print()}catch(e){toast(e.message,true)}finally{loading(false)}}
  async function printDetail(){if(!state.selectedDetail)return;loading(true);try{await logPrint('print_detail',1,state.selectedDetail.record?.id);$('#singlePrintArea').innerHTML=detailMarkup(state.selectedDetail,true);document.body.classList.add('printing-detail');window.print();setTimeout(()=>document.body.classList.remove('printing-detail'),500)}catch(e){toast(e.message,true)}finally{loading(false)}}
  async function exportCsv(){try{validateDates()}catch(e){return toast(e.message,true)}loading(true);try{const u=new URL(`${API_BASE}/admin/owner/records/export.csv`);u.searchParams.set('office_code',OFFICE_CODE);const q=new URLSearchParams(filters());[...q].forEach(([k,v])=>{if(v)u.searchParams.set(k,v)});if($('#includeInternal').checked)u.searchParams.set('include_internal','1');const r=await fetch(u,{headers:{'X-Admin-Session':state.adminSession}});if(!r.ok){const d=await r.json().catch(()=>({}));const e=new Error(d.error||`CSV出力に失敗しました（${r.status}）`);e.status=r.status;throw e}const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`homecare_records_${$('#dateFrom').value}_${$('#dateTo').value}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('CSVを保存しました。')}catch(e){if(e.status===401)logout(false);toast(e.message,true)}finally{loading(false)}}
  function resetFilters(){const today=ymd();$('#dateTo').value=today;$('#dateFrom').value=addDays(today,-30);$('#clientFilter').value='';$('#staffFilter').value='';$('#statusFilter').value='';$('#keywordFilter').value='';state.offset=0;search(true)}
  async function loadInitial(){const options=await api('/admin/owner/records/options');fillOptions(options);$('#versionLabel').textContent=CONFIG.APP_VERSION||'';$('#demoBanner').hidden=!demo;await search(true)}
  function bind(){
    $('#loginForm').addEventListener('submit',login);$('#clearAdminCode').addEventListener('click',()=>{$('#adminCode').value='';$('#adminCode').focus()});$('#logoutButton').addEventListener('click',()=>logout());$('#searchForm').addEventListener('submit',e=>{e.preventDefault();search(true)});$('#resetButton').addEventListener('click',resetFilters);$('#prevPage').addEventListener('click',()=>{state.offset=Math.max(0,state.offset-PAGE_SIZE);search(false)});$('#nextPage').addEventListener('click',()=>{state.offset+=PAGE_SIZE;search(false)});$('#csvButton').addEventListener('click',exportCsv);$('#printListButton').addEventListener('click',printList);$('#printDetailButton').addEventListener('click',printDetail);$('#closeDialog').addEventListener('click',()=>$('#recordDialog').close());$('#closeDialogButton').addEventListener('click',()=>$('#recordDialog').close());$('#recordDialog').addEventListener('click',e=>{if(e.target===$('#recordDialog'))$('#recordDialog').close()});window.addEventListener('afterprint',()=>document.body.classList.remove('printing-detail'))
  }
  async function init(){bind();$('#ownerBackLink').href=`owner.html${demo?'?demo=1':''}`;const today=ymd();$('#dateTo').value=today;$('#dateFrom').value=addDays(today,-30);$('#adminCode').value=demo?'1234':'';const saved=sessionStorage.getItem(STORAGE_KEY)||'';if(saved){state.adminSession=saved;loginView(false);try{await loadInitial()}catch(e){toast(e.message,true);if(e.status===401)logout(false)}}else if(demo){await login()}else loginView(true)}
  init().catch(e=>toast(e.message,true));
})();
