(() => {
  'use strict';
  const CONFIG=window.DPRO_HOMECARE_CONFIG||{};
  const API_BASE=String(CONFIG.API_BASE||'').replace(/\/+$/,'');
  const OFFICE_CODE=CONFIG.OFFICE_CODE||'dpro_homecare_demo';
  const TIMEOUT=Number(CONFIG.REQUEST_TIMEOUT_MS||15000);
  const STORAGE_KEY=CONFIG.OWNER_ADMIN_STORAGE_KEY||'dpro_homecare_owner_admin_code';
  const params=new URLSearchParams(location.search);
  const demo=['1','true','yes'].includes(String(params.get('demo')||'').toLowerCase());
  const state={adminCode:'',data:null,selectedLink:null};
  const $=(q,r=document)=>r.querySelector(q);const $$=(q,r=document)=>[...r.querySelectorAll(q)];
  const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const DAYS=[['mon','月曜日'],['tue','火曜日'],['wed','水曜日'],['thu','木曜日'],['fri','金曜日'],['sat','土曜日'],['sun','日曜日']];
  function toast(message,error=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error',error);el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4500)}
  function loading(active){$('#loadingOverlay').hidden=!active}
  async function api(path,options={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),TIMEOUT);const url=new URL(`${API_BASE}${path}`);if(!url.searchParams.has('office_code'))url.searchParams.set('office_code',OFFICE_CODE);const headers={'Content-Type':'application/json','X-Admin-Code':state.adminCode,...(options.headers||{})};try{const res=await fetch(url,{method:options.method||'GET',headers,signal:c.signal,...(options.body===undefined?{}:{body:JSON.stringify(options.body)})});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false){const e=new Error(data.error||`通信エラー（${res.status}）`);e.status=res.status;throw e}return data}catch(e){if(e.name==='AbortError')throw new Error('通信がタイムアウトしました。もう一度お試しください。');if(e.status===401)logout(false);throw e}finally{clearTimeout(t)}}
  function loginView(show){$('#loginPanel').hidden=!show;$('#settingsApp').hidden=show;$('#logoutButton').hidden=show}
  async function login(event){event?.preventDefault();state.adminCode=$('#adminCode').value.trim();if(!state.adminCode)return toast('管理コードを入力してください。',true);loading(true);try{await api('/admin/verify',{method:'POST',body:{admin_code:state.adminCode}});sessionStorage.setItem(STORAGE_KEY,state.adminCode);loginView(false);await loadSettings();toast('設定画面を開きました。')}catch(e){toast(e.message,true);loginView(true)}finally{loading(false)}}
  function logout(notify=true){state.adminCode='';state.data=null;sessionStorage.removeItem(STORAGE_KEY);$('#adminCode').value=demo?'1234':'';loginView(true);if(notify)toast('ログアウトしました。')}
  function renderHours(hours={}){$('#businessHours').innerHTML=DAYS.map(([key,label])=>{const d=hours[key]||{closed:['sat','sun'].includes(key),open:'09:00',close:'18:00'};return `<div class="hours-row ${d.closed?'closed':''}" data-day="${key}"><strong>${label}</strong><label class="closed-label"><input type="checkbox" data-closed ${d.closed?'checked':''}>休業</label><input type="time" data-open step="1800" value="${esc(d.open||'09:00')}"><input type="time" data-close step="1800" value="${esc(d.close||'18:00')}"></div>`}).join('');$$('.hours-row [data-closed]').forEach(x=>x.addEventListener('change',()=>x.closest('.hours-row').classList.toggle('closed',x.checked)))}
  function fill(data){state.data=data;const o=data.office||{},s=data.settings||{};$('#pageOfficeName').textContent=o.office_name||'訪問介護事業所';$('#officeName').value=o.office_name||'';$('#managerName').value=o.manager_name||'';$('#officePhone').value=o.phone||'';$('#emergencyPhone').value=o.emergency_phone||'';$('#fax').value=o.fax||'';$('#email').value=o.email||'';$('#postalCode').value=o.postal_code||'';$('#address').value=o.address||'';$('#earlyLimit').value=s.visit_start_early_limit_minutes??30;$('#delayAlert').value=s.visit_delay_alert_minutes??15;$('#signedUrlMinutes').value=s.signed_url_minutes??10;$('#familyApproval').checked=s.family_report_requires_approval!==false;$('#allowLocation').checked=s.allow_staff_location===true;$('#familyPortalEnabled').checked=s.family_portal_enabled!==false;$('#memberPortalEnabled').checked=s.member_portal_enabled!==false;$('#lineAccountName').value=s.line_official_account_name||'';$('#lineAccountUrl').value=s.line_official_account_url||'';$('#identityMatchRequired').checked=s.line_link_identity_match_required!==false;$('#publicNotice').value=s.public_notice||'';$('#emergencyNote').value=s.emergency_contact_note||'';$('#settingsVersion').textContent=`version ${s.settings_version??'-'}`;renderHours(s.business_hours);renderLinks(data.line_links||{pending:[],history:[],counts:{}});$('#demoBanner').hidden=!demo}
  function linkRole(v){return v==='client'?'ご本人':'ご家族'}function status(v){return ({pending:'申請中',approved:'承認済み',rejected:'却下',cancelled:'取消'})[v]||v}
  function renderLinks(info){const c=info.counts||{};$('#pendingLinkCount').textContent=c.pending||0;$('#lineTabBadge').textContent=c.pending||0;$('#summaryPending').textContent=c.pending||0;$('#summaryApproved').textContent=c.approved||0;$('#summaryRejected').textContent=c.rejected||0;const pending=info.pending||[];$('#pendingLinkList').innerHTML=pending.length?pending.map(x=>`<article class="link-card"><div class="link-main"><h3>${esc(x.applicant_name)}・${esc(linkRole(x.requested_role))}</h3><p>${esc(x.applicant_phone||'電話未登録')}／申請 ${esc(formatDate(x.created_at))}</p><p class="link-detail">利用者：${esc(x.client?.client_name||'自動照合なし')} ${x.client?`（${esc(x.client.client_number)}）`:''}</p><p class="link-detail">登録家族：${esc(x.family?.family_name||'新規または未照合')} ${x.family?.relationship?`・${esc(x.family.relationship)}`:''}</p></div><div class="link-actions"><span class="status-pill warning">申請中</span><button class="button button-secondary" data-reject="${x.id}" type="button">却下</button><button class="button button-primary" data-approve="${x.id}" type="button">確認・承認</button></div></article>`).join(''):'<div class="empty-box">承認待ちのLINE連携申請はありません。</div>';const history=info.history||[];$('#linkHistoryList').innerHTML=history.length?history.map(x=>`<article class="link-card"><div class="link-main"><h3>${esc(x.applicant_name)}・${esc(linkRole(x.requested_role))}</h3><p>${esc(x.client?.client_name||'利用者未指定')}／処理 ${esc(formatDate(x.processed_at||x.updated_at))}</p>${x.rejection_reason?`<p class="link-detail">理由：${esc(x.rejection_reason)}</p>`:''}</div><div class="link-actions"><span class="status-pill ${x.status==='rejected'?'danger':''}">${esc(status(x.status))}</span></div></article>`).join(''):'<div class="empty-box">処理履歴はありません。</div>';$$('[data-approve]').forEach(b=>b.addEventListener('click',()=>openApprove(b.dataset.approve)));$$('[data-reject]').forEach(b=>b.addEventListener('click',()=>rejectLink(b.dataset.reject)))}
  function formatDate(iso){if(!iso)return'未登録';return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}
  async function loadSettings(){loading(true);try{fill(await api('/admin/settings'))}catch(e){toast(e.message,true)}finally{loading(false)}}
  function collectHours(){const h={};$$('.hours-row').forEach(row=>{h[row.dataset.day]={closed:$('[data-closed]',row).checked,open:$('[data-open]',row).value,close:$('[data-close]',row).value}});return h}
  async function saveSettings(event){event.preventDefault();const payload={office_name:$('#officeName').value.trim(),manager_name:$('#managerName').value.trim(),phone:$('#officePhone').value.trim(),emergency_phone:$('#emergencyPhone').value.trim(),fax:$('#fax').value.trim(),email:$('#email').value.trim(),postal_code:$('#postalCode').value.trim(),address:$('#address').value.trim(),visit_start_early_limit_minutes:Number($('#earlyLimit').value),visit_delay_alert_minutes:Number($('#delayAlert').value),signed_url_minutes:Number($('#signedUrlMinutes').value),family_report_requires_approval:$('#familyApproval').checked,allow_staff_location:$('#allowLocation').checked,family_portal_enabled:$('#familyPortalEnabled').checked,member_portal_enabled:$('#memberPortalEnabled').checked,line_official_account_name:$('#lineAccountName').value.trim(),line_official_account_url:$('#lineAccountUrl').value.trim(),line_link_identity_match_required:$('#identityMatchRequired').checked,public_notice:$('#publicNotice').value.trim(),emergency_contact_note:$('#emergencyNote').value.trim(),business_hours:collectHours()};loading(true);try{const r=await api('/admin/settings/update',{method:'POST',body:payload});toast(`設定を保存しました（version ${r.settings_version}）`);await loadSettings()}catch(e){toast(e.message,true)}finally{loading(false)}}
  function openApprove(id){const link=(state.data?.line_links?.pending||[]).find(x=>x.id===id);if(!link)return;state.selectedLink=link;$('#approveApplicant').textContent=`${link.applicant_name} 様`;$('#approveRequestDetail').innerHTML=`<strong>${esc(linkRole(link.requested_role))}として申請</strong><br>${esc(link.applicant_phone||'電話未登録')}<br>自動照合：${esc(link.client?.client_name||'なし')}`;$('#approveClient').innerHTML='<option value="">選択してください</option>'+(state.data.clients||[]).map(c=>`<option value="${c.id}" ${c.id===link.client_id?'selected':''}>${esc(c.client_number)}・${esc(c.client_name)}</option>`).join('');$('#approveRelationship').value=link.requested_role==='client'?'本人':(link.family?.relationship||'');$('#consentNote').value='登録情報と申請内容を確認';updateFamilyOptions();$('#approveDialog').showModal()}
  function updateFamilyOptions(){const clientId=$('#approveClient').value;const link=state.selectedLink;const rows=(state.data?.families||[]).filter(f=>f.client_id===clientId);$('#approveFamily').innerHTML='<option value="">新しい家族情報として登録</option>'+rows.map(f=>`<option value="${f.id}" ${f.id===link?.family_member_id?'selected':''}>${esc(f.family_name)}・${esc(f.relationship||'続柄未登録')}</option>`).join('')}
  async function approveLink(event){event.preventDefault();if(!state.selectedLink)return;const body={client_id:$('#approveClient').value,family_member_id:$('#approveFamily').value||null,relationship:$('#approveRelationship').value.trim(),can_view_schedules:$('#canViewSchedules').checked,can_view_reports:$('#canViewReports').checked,can_send_messages:$('#canSendMessages').checked,can_manage_family:$('#canManageFamily').checked,consent_note:$('#consentNote').value.trim()};if(!body.client_id&&!body.family_member_id)return toast('紐付ける利用者を選択してください。',true);if(!confirm(`${state.selectedLink.applicant_name}様のLINE連携を承認しますか？`))return;loading(true);try{await api(`/admin/line-links/${state.selectedLink.id}/approve`,{method:'POST',body});$('#approveDialog').close();toast('LINE連携を承認しました。');await loadSettings()}catch(e){toast(e.message,true)}finally{loading(false)}}
  async function rejectLink(id){const link=(state.data?.line_links?.pending||[]).find(x=>x.id===id);if(!link)return;const reason=prompt(`${link.applicant_name}様の申請を却下する理由を入力してください。`,'登録情報を確認できませんでした。');if(!reason?.trim())return;loading(true);try{await api(`/admin/line-links/${id}/reject`,{method:'POST',body:{rejection_reason:reason.trim()}});toast('LINE連携申請を却下しました。');await loadSettings()}catch(e){toast(e.message,true)}finally{loading(false)}}
  function setTab(name){$$('.tab-button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));scrollTo({top:0,behavior:'smooth'})}
  function bind(){$('#loginForm').addEventListener('submit',login);$('#clearAdminCode').addEventListener('click',()=>$('#adminCode').value='');$('#logoutButton').addEventListener('click',()=>logout());$('#reloadButton').addEventListener('click',()=>state.adminCode?loadSettings():login());$('#settingsForm').addEventListener('submit',saveSettings);$$('.tab-button').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));$('#approveClient').addEventListener('change',updateFamilyOptions);$('#approveForm').addEventListener('submit',approveLink);$('#closeApproveDialog').addEventListener('click',()=>$('#approveDialog').close());$('#cancelApprove').addEventListener('click',()=>$('#approveDialog').close())}
  async function init(){bind();$('#adminCode').value=demo?'1234':'';state.adminCode=sessionStorage.getItem(STORAGE_KEY)||'';if(demo)state.adminCode='1234';if(state.adminCode){$('#adminCode').value=state.adminCode;loginView(false);await loadSettings()}else loginView(true)}
  init().catch(e=>toast(e.message,true));
})();
