(() => {
  'use strict';
  const C=window.DPRO_HOMECARE_CONFIG||{};const API=String(C.API_BASE||'').replace(/\/+$/,'');const OFFICE=C.OFFICE_CODE||'dpro_homecare_demo';const params=new URLSearchParams(location.search);const demo=['1','true','yes'].includes(String(params.get('demo')||'').toLowerCase());const $=(q,r=document)=>r.querySelector(q);
  const state={result:null,pages:[]};
  const PAGES=[['LINE連携入口','index.html?demo=1'],['家族画面','family.html?demo=1'],['本人画面','member.html?demo=1'],['予定管理','schedule.html?demo=1'],['スタッフ画面','staff.html?demo=1'],['オーナーPC','owner.html?demo=1'],['責任者iPad','owner-ipad.html?demo=1'],['事業所設定','settings.html?demo=1'],['system-check','system-check.html?demo=1']];
  function toast(m,e=false){const x=$('#toast');x.textContent=m;x.classList.toggle('error',e);x.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>x.hidden=true,4300)}function loading(v){$('#loadingOverlay').hidden=!v}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function groupName(key){if(/^(worker|supabase|office$|settings$|required|rls|private|production|phone|admin)/.test(key))return'基盤・接続';if(/^(family|line_)/.test(key))return'LINE・本人・家族';if(/^(schedule|recurring|visit_slot|client_overlap|staff_overlap|assignment|multi_staff|visit_change)/.test(key))return'訪問予定・割当て';if(/^staff_/.test(key)||/^(single_active|visit_start|visit_finish|required_plan)/.test(key))return'スタッフ業務';if(/^owner_/.test(key))return'オーナー管理';if(/^settings_/.test(key)||key==='system_check_ui')return'設定・営業前確認';return'その他'}
  function renderApi(result){const groups=new Map();(result.items||[]).forEach(i=>{const n=groupName(i.key);if(!groups.has(n))groups.set(n,[]);groups.get(n).push(i)});$('#apiGroups').innerHTML=[...groups].map(([n,rows])=>`<section class="group-block"><h3>${esc(n)}（${rows.filter(x=>x.ok).length}/${rows.length}）</h3>${rows.map(i=>`<div class="check-row"><span class="check-icon ${i.ok?'good':'bad'}">${i.ok?'✓':'!'}</span><strong>${esc(i.label)}</strong><span>${esc(i.detail)}</span></div>`).join('')}</section>`).join('')}
  async function checkPages(){const base=new URL('.',location.href);state.pages=await Promise.all(PAGES.map(async([label,path])=>{const u=new URL(path,base);u.searchParams.set('_check',Date.now());try{const r=await fetch(u,{cache:'no-store'});return{label,path,ok:r.ok,status:r.status}}catch(e){return{label,path,ok:false,status:0,error:e.message}}}));$('#pageChecks').innerHTML=state.pages.map(p=>`<div class="page-row"><span class="check-icon ${p.ok?'good':'bad'}">${p.ok?'✓':'!'}</span><strong>${esc(p.label)}</strong><a href="${esc(p.path)}" target="_blank">${p.ok?'開く':`HTTP ${p.status||'失敗'}`}</a></div>`).join('');return state.pages.every(p=>p.ok)}
  function renderSummary(apiOk,pageOk){const r=state.result||{};const failed=Number(r.failed||0)+(pageOk?0:state.pages.filter(p=>!p.ok).length);const passed=Number(r.passed||0)+state.pages.filter(p=>p.ok).length;$('#summaryGrid').innerHTML=[['API検査',`${r.passed||0}/${r.total||0}`],['公開画面',`${state.pages.filter(p=>p.ok).length}/${state.pages.length}`],['LINE申請中',r.operations?.pending_line_links??'-'],['総合エラー',failed]].map(([l,v])=>`<article><span>${esc(l)}</span><strong>${esc(v)}</strong></article>`).join('');const ok=apiOk&&pageOk;$('#overallCard').className=`overall-card ${ok?'good':'bad'}`;$('#overallText').textContent=ok?'すべて正常':'要確認';$('#overallCount').textContent=`合格 ${passed}／異常 ${failed}`}
  async function run(){loading(true);try{const url=new URL(`${API}/system-check`);url.searchParams.set('office_code',OFFICE);const [res,pageOk]=await Promise.all([fetch(url,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}),checkPages()]);state.result=res;renderApi(res);renderSummary(res.all_ok===true,pageOk);toast(res.all_ok&&pageOk?'すべての検査に合格しました。':'異常項目を確認してください。',!(res.all_ok&&pageOk))}catch(e){toast(e.message,true);$('#overallCard').className='overall-card bad';$('#overallText').textContent='通信失敗'}finally{loading(false)}}
  async function prepare(){const code=$('#adminCode').value.trim();if(!code)return toast('管理コードを入力してください。',true);if(!confirm('デモデータを重複なく再準備しますか？'))return;loading(true);try{const url=new URL(`${API}/demo/prepare`);url.searchParams.set('office_code',OFFICE);const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Code':code},body:JSON.stringify({admin_code:code})});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'デモ準備に失敗しました。');toast('デモデータを準備しました。');await run()}catch(e){toast(e.message,true)}finally{loading(false)}}
  async function copyJson(){if(!state.result)return toast('先に一括チェックを実行してください。',true);try{await navigator.clipboard.writeText(JSON.stringify({...state.result,public_pages:state.pages},null,2));toast('検査JSONをコピーしました。')}catch{toast('コピーできませんでした。',true)}}
  function renderUrls(){const base=new URL('.',location.href);const rows=[['製品入口',new URL('index.html?demo=1',base)],['家族画面',new URL('family.html?demo=1',base)],['本人画面',new URL('member.html?demo=1',base)],['予定管理',new URL('schedule.html?demo=1',base)],['スタッフ画面',new URL('staff.html?demo=1',base)],['オーナーPC',new URL('owner.html?demo=1',base)],['責任者iPad',new URL('owner-ipad.html?demo=1',base)],['事業所設定',new URL('settings.html?demo=1',base)],['Worker API',new URL(`${API}/`)],['system-check API',new URL(`${API}/system-check`)]];$('#urlList').innerHTML=rows.map(([l,u])=>`<a class="url-item" href="${esc(u.href)}" target="_blank"><strong>${esc(l)}</strong><code>${esc(u.href)}</code></a>`).join('');const sys=new URL(`${API}/system-check`);sys.searchParams.set('office_code',OFFICE);$('#workerSystemLink').href=sys.href}
  function init(){renderUrls();$('#demoBanner').hidden=!demo;$('#adminCode').value=demo?'1234':'';$('#clearAdminCode').addEventListener('click',()=>$('#adminCode').value='');$('#runCheck').addEventListener('click',run);$('#prepareDemo').addEventListener('click',prepare);$('#copyJson').addEventListener('click',copyJson);run()}
  init();
})();
